@startuml
[*] --> Rfq.CREATED

Rfq.CREATED -> Rfq.REJECTED : Responder not interested
Rfq.CREATED --> Rfq.QUOTED : Responder\nquotes
Rfq.CREATED --> Rfq.EXPIRED : No response\nbefore timeout

Rfq.QUOTED --> Rfq.COUNTERED : Requestor proposes\nnew price
Rfq.QUOTED --> Rfq.ACCEPTED : Requestor accepts\nprice
Rfq.QUOTED --> Rfq.REJECTED : Requestor rejects price\nand terminates Rfq
Rfq.QUOTED --> Rfq.EXPIRED : No response\nbefore timeout

Rfq.CREATED --> Rfq.CANCELED : Requestor\ncancels Rfq
Rfq.QUOTED --> Rfq.CANCELED : Requestor\ncancels Rfq
Rfq.COUNTERED --> Rfq.EXPIRED :  No response\nbefore timeout
Rfq.COUNTERED --> Rfq.CANCELED :  Requestor cancels Rfq
Rfq.COUNTERED --> Rfq.COUNTERED : Responder proposes\nnew price\nfollowing COUNTERED
Rfq.COUNTERED --> Rfq.ACCEPTED : Requestor accepts\nnew price
Rfq.COUNTERED --> Rfq.ACCEPTED : Responder accepts\nnew price
Rfq.COUNTERED --> Rfq.REJECTED : Requestor rejects price\nand terminates Rfq
Rfq.COUNTERED --> Rfq.REJECTED : Responder rejects price\nand terminates Rfq

Rfq.ACCEPTED --> Rfq.COMPLETED : Rfq is accepted,\nTrade is created

Rfq.REJECTED --> [*] : Rfq is rejected\nand terminates
Rfq.COMPLETED --> [*] : Rfq is completed\nand terminates
Rfq.CANCELED --> [*] : Rfq is canceled\nand terminates
Rfq.EXPIRED --> [*] : Rfq expires\nand terminates

UserDisconnect -down-> Rfq.CANCELED : If cancel\non disconnect

@enduml
