// EIDER HELPER GENERATED BY EIDER AT 2020-05-31T13:48:33.250665Z. DO NOT MODIFY

package com.aeroncookbook.cluster.rsm.protocol;

import org.agrona.DirectBuffer;

public final class EiderHelper
{
    /**
     * private constructor.
     */
    private EiderHelper()
    {
        //unused;
    }

    /**
     * Reads the Eider Id from the buffer at the offset provided.
     */
    public static short getEiderId(DirectBuffer buffer, int offset)
    {
        return buffer.getShort(offset, java.nio.ByteOrder.LITTLE_ENDIAN);
    }
}
